
name: Terraform AZ-700 Private Link Service Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terrafrom-deploy.yml'

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

jobs:
  terraform-dev:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Terraform Repo
      - name: Checkout Terraform Repo
        uses: actions/checkout@v4
        with:
          repository: az-700-network-engineer-associate/terraform-az700-networking
          token: ${{ secrets.TF_REPO_TOKEN }}
          path: env/dev/private-link-service

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3️⃣ Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      # 4️⃣ Terraform Init
      - name: Terraform Init
        working-directory: terraform/envs/dev/private-link-service
        run: terraform init

      # 5️⃣ Terraform Validate
      - name: Terraform Validate
        working-directory: terraform/envs/dev/private-link-service
        run: terraform validate

      # 6️⃣ Terraform Plan
      - name: Terraform Plan
        working-directory: terraform/envs/dev/private-link-service
        run: terraform plan -out=tfplan

      # 7️⃣ Terraform Apply
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform/envs/dev/private-link-service
        run: terraform apply -auto-approve tfplan

